config/routes.rb
RailsTask2::Application.routes.draw do

    resources :days do 
        resources :tasks
    end
    resources :tasks

end

app/models/day.rb
class Day < ActiveRecord::Base
    has_many :tasks, :dependent => :destroy
end

app/models/task.rb
class Task < ActiveRecord::Base
    belongs_to :day
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
    def index
        @query = Day.where( ["date >= ?", Date.today] ).order( "date ASC" )[0..6]
       
        @days = []
 
        for i in 0..@query.length-1 do
          
            @days << @query[i]

            # if there can be a gap between this element and next
            if i != @query.length-1
                if @query[i].date != @query[i+1].date - 1
                    @days << nil
                end
            end
        end
    end

    def show
        @day = Day.find(params[:id])
    end
    def new
        @day = Day.new 
    end
    
    def create
       y = params[:post_date][6..9].to_i
       m = params[:post_date][3..4].to_i
       d = params[:post_date][0..1].to_i
       @day = Day.new
       @day.date = DateTime.new(y, m, d) 
       @day.save 
       redirect_to :days 
    end    
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    def new
        @task = Day.find(params[:day_id]).tasks.new
    end

    def show
        @task = Task.find(params[:id])
    end

    def create
        day = Day.find( params[:day_id] )
        day.tasks.create( params[:task] )
        redirect_to day
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/days/index.html.haml
%h2 Rails'owy Kalendarz

- @days.each do |day|
  - if day != nil
    %table{ :style => "float: left; border: black 1px solid; height: 400px; width: 160px;" }
      %th{ :style => "background: #888888;"}
        = link_to day.date, day
      - day.tasks.order("hour ASC").each do |task|
        %tr
          - if task != nil
            %td
              %b= task.hour.to_s + ":00"
              =task.name
          - else
            %td= link_to "(+)", new_day_task_path(day)
  - else
    %p{ :style => "float: left; margin: 200px 0 0 0;" } (...)

%p{ :style => "clear: both; height: 20px;" } 
%p= link_to "Dodaj nowy dzień", new_day_path
%p
%p
%p - (...) oznacza, ze pomiedzy dniami kalendarza jest min. 1-dniowa przerwa

app/views/days/new.html.haml
%h2 Dodaj dzien (zajec) 

-#- form_for @day do |form|
-#  #left{ :style => "float: left;" }
-#    %p= form.label :date, "Data (dd-mm-rrrr)"
-#    %p= form.text_area "aaa", :style => "height: 20px;" 
-#%p{ :style => "clear: both;" }= form.submit "Dodaj"

- form_tag :action => "create", :method => "post" do 
  %p= label_tag "Data (dd-mm-rrrr):"
  %p= text_field_tag(:post_date)
  %p= submit_tag "Dodaj"

app/views/days/show.html.haml
%h2= @day.date

- @day.tasks.order("hour ASC").each do |task|
  %b= task.hour.to_s + ":00"
  = link_to task.name, task
  %p{ :style => "margin: 0 0 0 20px;"}= task.description

%p
%p= link_to "Dodaj zadanie", new_day_task_path(@day)
%p
%p= link_to "<< Wstecz", days_path()

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsTask2</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tasks/new.html.haml
%h2 Dodaj zadanie
%h3= "na dzien " + @task.day.date.to_s

- form_for [@task.day, @task] do |form|
  #left{ :style => "float: left;" }
    %p= form.label :name, "Nazwa"
    %p= form.text_area :name, :style => "height: 20px;" 
    %p= form.label :hour, "Godzina (hh)"
    %p= form.text_area :hour, :style => "height: 20px;"

  #right{ :style => "float: left;" }
    %p= form.label :description, "Opis"
    %p= form.text_area :description
  %p{ :style => "clear: both;" }= form.submit "Dodaj"

app/views/tasks/show.html.haml
%h2 Opis zadania

%b= @task.hour.to_s + ":00"
= @task.name
%p
%p=@task.description